/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_com_mzsw_PesoLibWrapper */

#ifndef _Included_br_com_mzsw_PesoLibWrapper
#define _Included_br_com_mzsw_PesoLibWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef br_com_mzsw_PesoLibWrapper_EVENTO_CANCELADO
#define br_com_mzsw_PesoLibWrapper_EVENTO_CANCELADO 0L
#undef br_com_mzsw_PesoLibWrapper_EVENTO_CONECTADO
#define br_com_mzsw_PesoLibWrapper_EVENTO_CONECTADO 1L
#undef br_com_mzsw_PesoLibWrapper_EVENTO_DESCONECTADO
#define br_com_mzsw_PesoLibWrapper_EVENTO_DESCONECTADO 2L
#undef br_com_mzsw_PesoLibWrapper_EVENTO_PESORECEBIDO
#define br_com_mzsw_PesoLibWrapper_EVENTO_PESORECEBIDO 3L
/*
 * Class:     br_com_mzsw_PesoLibWrapper
 * Method:    criar
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_br_com_mzsw_PesoLibWrapper_criar
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_com_mzsw_PesoLibWrapper
 * Method:    isConectado
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_br_com_mzsw_PesoLibWrapper_isConectado
  (JNIEnv *, jobject, jlong);

/*
 * Class:     br_com_mzsw_PesoLibWrapper
 * Method:    setConfiguracao
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_com_mzsw_PesoLibWrapper_setConfiguracao
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     br_com_mzsw_PesoLibWrapper
 * Method:    getConfiguracao
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_com_mzsw_PesoLibWrapper_getConfiguracao
  (JNIEnv *, jobject, jlong);

/*
 * Class:     br_com_mzsw_PesoLibWrapper
 * Method:    getMarcas
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_com_mzsw_PesoLibWrapper_getMarcas
  (JNIEnv *, jobject, jlong);

/*
 * Class:     br_com_mzsw_PesoLibWrapper
 * Method:    getModelos
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_com_mzsw_PesoLibWrapper_getModelos
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     br_com_mzsw_PesoLibWrapper
 * Method:    aguardaEvento
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_br_com_mzsw_PesoLibWrapper_aguardaEvento
  (JNIEnv *, jobject, jlong);

/*
 * Class:     br_com_mzsw_PesoLibWrapper
 * Method:    getUltimoPeso
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_br_com_mzsw_PesoLibWrapper_getUltimoPeso
  (JNIEnv *, jobject, jlong);

/*
 * Class:     br_com_mzsw_PesoLibWrapper
 * Method:    solicitaPeso
 * Signature: (JF)Z
 */
JNIEXPORT jboolean JNICALL Java_br_com_mzsw_PesoLibWrapper_solicitaPeso
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     br_com_mzsw_PesoLibWrapper
 * Method:    cancela
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_br_com_mzsw_PesoLibWrapper_cancela
  (JNIEnv *, jobject, jlong);

/*
 * Class:     br_com_mzsw_PesoLibWrapper
 * Method:    libera
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_br_com_mzsw_PesoLibWrapper_libera
  (JNIEnv *, jobject, jlong);

/*
 * Class:     br_com_mzsw_PesoLibWrapper
 * Method:    getVersao
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_com_mzsw_PesoLibWrapper_getVersao
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
